In [36]:
import pandas as pd
import numpy as np

from sklearn.cross_validation import train_test_split
#from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

from sklearn.semi_supervised import LabelPropagation, LabelSpreading

#from sklearn.model_selection import cross_val_score
from sklearn.cross_validation import cross_val_score

#import time #処理時間の計測用

import os


In [37]:
train_data = pd.read_csv("vardata_4.csv", encoding="shift-jis", header=1)
#train_data.to_csv('vardata_3.csv', encoding="shift-jis")
train_data

・  .  %  ％  0  1  10  100  1000  2 ...  労働  論  論点  論理  話  話し  話そ  話題  枠  \
0    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
1    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
2    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  1   0   0   0  0   
3    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   1   0   0  0   
4    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
5    0  0  0  0  0  0   1    0     0  0 ...   0  0   0   0  0   0   0   0  0   
6    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
7    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
8    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
9    0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
10   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
11   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
12   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
13   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  1   0   0   0  0   
14   0  0  0  0  0  0   1    0     1  0 ...   0  0   0   0  0   0   0   0  0   
15   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
16   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
17   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
18   0  0  0  0  0  0   1    1     0  0 ...   0  0   0   0  0   0   0   0  0   
19   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
20   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
21   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
22   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
23   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
24   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
25   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
26   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
27   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
28   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
29   0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
..  .. .. .. .. .. ..  ..  ...   ... .. ...  .. ..  ..  .. ..  ..  ..  .. ..   
918  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
919  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
920  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
921  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
922  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
923  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
924  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
925  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
926  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
927  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
928  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
929  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
930  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
931  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
932  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
933  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
934  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
935  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   
936  

In [38]:
list_ = range(1,len(train_data)+1)
list_ = np.array(list_)
list_df = pd.DataFrame(list_)
list_df = list_df.rename(columns={0: 'id'})
train_data = pd.concat([train_data, list_df], axis=1)
train_data

・  .  %  ％  0  1  10  100  1000  2 ...   論  論点  論理  話  話し  話そ  話題  枠  綺麗  \
0    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
1    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
2    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  1   0   0   0  0   0   
3    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   1   0   0  0   0   
4    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
5    0  0  0  0  0  0   1    0     0  0 ...   0   0   0  0   0   0   0  0   0   
6    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
7    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
8    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
9    0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
10   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
11   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
12   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
13   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  1   0   0   0  0   0   
14   0  0  0  0  0  0   1    0     1  0 ...   0   0   0  0   0   0   0  0   0   
15   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
16   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
17   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
18   0  0  0  0  0  0   1    1     0  0 ...   0   0   0  0   0   0   0  0   0   
19   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
20   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
21   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
22   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
23   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
24   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
25   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
26   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
27   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
28   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
29   0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
..  .. .. .. .. .. ..  ..  ...   ... .. ...  ..  ..  .. ..  ..  ..  .. ..  ..   
918  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
919  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
920  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
921  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
922  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
923  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
924  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
925  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
926  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
927  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
928  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
929  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
930  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
931  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
932  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
933  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
934  0  0  0  0  0  0   0    0     0  0 ...   0   0   0  0   0   0   0  0   0   
935  0  0  0  0  0  0   0    0     0

In [39]:
train_data_2 = pd.read_csv("train_data_5.csv", encoding="shift_jis")
train_data_2

text  a  b  c  d  e  f   id   label
0                                        そうっすね  0  1  2  0  0  0    1   12000
1                           そこは話が変わるので一旦スコープ外で  0  0  0  0  0  2    2       2
2                               さっき話していた感じで良くて  0  2  0  0  0  1    3   20001
3                                 前のあのやってくれたやつ  0  1  0  0  0  1    4   10001
4                            10個でグルーピングしてくれたやつ  0  1  0  0  0  1    5   10001
5                                5月の資料にあった気がする  2  0  0  0  0  0    6  200000
6                                相当時間経ってますよね実は  0  0  0  0  0  1    7       1
7                                        そうですね  0  0  2  0  0  0    8    2000
8                                        一番上です  2  0  0  0  0  0    9  200000
9                                         そうです  0  0  2  0  0  0   10    2000
10                              それの8ページ目からやります  1  0  0  0  0  1   11  100001
11                    その時は教師データ作成に役立てると言っていたよね  2  0  0  0  0  0   12  200000
12                                今とは話が変わってますね  0  0  2  0  0  0   13    2000
13                    結果1000件を教師としてトピック数は10こです  2  0  0  0  0  0   14  200000
14                             これだとちょっと少なすぎるかな  0  1  0  2  0  0   15   10200
15          これを見てなんだろうな結局やりたいものができるかどうか見ていくのかな  0  1  0  0  0  1   16   10001
16                        ちょっとやってみないとわかんないですよね  0  1  1  0  0  0   17   11000
17               今は10だけど手続き100個だからもう少し増やしてみようか  0  0  0  0  2  0   18      20
18                            これでもあの人見ていないですよね  0  0  0  0  0  2   19       2
19                            邪魔な文字が多いのではないですか  1  0  0  0  0  1   20  100001
20              邪魔な文字を取り除いて分析をした方がいいのではないでしょうか  0  0  0  0  2  0   21      20
21   それがトピックを構成する重要な要素であれば取り除かない方がいいのではないでしょうか  1  0  0  2  0  0   22  100200
22                      形態素した後に外すっていうイメージでしょうか  0  0  0  0  2  1   23      21
23                                  そういう世界なのかな  0  0  2  0  0  0   24    2000
24                               そうなのかもしれないですね  0  0  2  0  0  0   25    2000
25                     最初の段階から除くべきものが外せるんでしょうね  0  1  0  0  0  2   26   10002
26                最適なトピック数が分からないという問題はあるんでしょうね  0  0  0  2  0  1   27     201
27                       辞書作成はやったらいいので置いときましょう  1  0  2  0  0  0   28  102000
28                     FAQに紐付けるっていうのはどうなんでしょうね  0  1  0  2  0  0   29   10200
29          目でやるというのは何を持ってFAQと紐付けたのかわからなくなるのでは  0  0  0  2  0  1   30     201
..                                         ... .. .. .. .. .. ..  ...     ...
917                                       バス会社  0  0  0  0  0  0  925       0
918                                     素晴らしいね  0  2  0  0  0  0  926   20000
919                           明日以降ってまだ来れなくしたこと  0  0  0  2  0  0  927     200
920                              何でも拾ってんだろうねこれ  0  2  0  0  0  0  928   20000
921                                         暑い  0  2  0  0  0  0  929   20000
922                             最近どういうのか直感になるの  0  2  0  0  0  0  930   20000
923                         空白の時間をうまく拾うのが難しいよね  0  2  0  0  0  0  931   20000
924                                 ちゃんと動いてるかな  0  2  0  0  0  0  932   20000
925                                 たぶんねあれだと思う  0  2  0  0  0  0  933   20000
926                                  プリントできるかな  0  2  0  0  0  0  934   20000
927                                うまくサイトに飛ぶかな  0  2  0  0  0  0  935   20000
928                                喋ってるのあったら見て  0  0  0  0  0  0  936       0
929                            誰が喋ってるか分かるか分かるし  0  2  0  0  0  0  937   20000
930                         ずっとこれ今聞いてる状態って言うこと  0  2  0  0  0  0  938   20000
931                         今日の打ち合わせがうまくするといいな  0  0  2  0  0  0  939    2000
932                                   雨降ってましたよ  2  0  0  0  0  0  940  200000
933                                 今日は良い天気ですね  2  0  0  0  0  0  941  200000
934                                      ございます  0  0  0  0  0  0  942       0
935                                        NaN  0  0  0  0  0  0  943       0
936                                        NaN  0  0  0  0  0  0

In [40]:
dataset_label = pd.merge(train_data, train_data_2, how="inner", on="id")
dataset_label

・  .  %  ％  0  1  10  100  1000  2   ...    綺麗   id  \
0    0  0  0  0  0  0   0    0     0  0   ...     0    1   
1    0  0  0  0  0  0   0    0     0  0   ...     0    2   
2    0  0  0  0  0  0   0    0     0  0   ...     0    3   
3    0  0  0  0  0  0   0    0     0  0   ...     0    4   
4    0  0  0  0  0  0   0    0     0  0   ...     0    5   
5    0  0  0  0  0  0   1    0     0  0   ...     0    6   
6    0  0  0  0  0  0   0    0     0  0   ...     0    7   
7    0  0  0  0  0  0   0    0     0  0   ...     0    8   
8    0  0  0  0  0  0   0    0     0  0   ...     0    9   
9    0  0  0  0  0  0   0    0     0  0   ...     0   10   
10   0  0  0  0  0  0   0    0     0  0   ...     0   11   
11   0  0  0  0  0  0   0    0     0  0   ...     0   12   
12   0  0  0  0  0  0   0    0     0  0   ...     0   13   
13   0  0  0  0  0  0   0    0     0  0   ...     0   14   
14   0  0  0  0  0  0   1    0     1  0   ...     0   15   
15   0  0  0  0  0  0   0    0     0  0   ...     0   16   
16   0  0  0  0  0  0   0    0     0  0   ...     0   17   
17   0  0  0  0  0  0   0    0     0  0   ...     0   18   
18   0  0  0  0  0  0   1    1     0  0   ...     0   19   
19   0  0  0  0  0  0   0    0     0  0   ...     0   20   
20   0  0  0  0  0  0   0    0     0  0   ...     0   21   
21   0  0  0  0  0  0   0    0     0  0   ...     0   22   
22   0  0  0  0  0  0   0    0     0  0   ...     0   23   
23   0  0  0  0  0  0   0    0     0  0   ...     0   24   
24   0  0  0  0  0  0   0    0     0  0   ...     0   25   
25   0  0  0  0  0  0   0    0     0  0   ...     0   26   
26   0  0  0  0  0  0   0    0     0  0   ...     0   27   
27   0  0  0  0  0  0   0    0     0  0   ...     0   28   
28   0  0  0  0  0  0   0    0     0  0   ...     0   29   
29   0  0  0  0  0  0   0    0     0  0   ...     0   30   
..  .. .. .. .. .. ..  ..  ...   ... ..   ...    ..  ...   
911  0  0  0  0  0  0   0    0     0  0   ...     0  919   
912  0  0  0  0  0  0   0    0     0  0   ...     0  920   
913  0  0  0  0  0  0   0    0     0  0   ...     0  921   
914  0  0  0  0  0  0   0    0     0  0   ...     0  922   
915  0  0  0  0  0  0   0    0     0  0   ...     0  923   
916  0  0  0  0  0  0   0    0     0  0   ...     0  924   
917  0  0  0  0  0  0   0    0     0  0   ...     0  925   
918  0  0  0  0  0  0   0    0     0  0   ...     0  926   
919  0  0  0  0  0  0   0    0     0  0   ...     0  927   
920  0  0  0  0  0  0   0    0     0  0   ...     0  928   
921  0  0  0  0  0  0   0    0     0  0   ...     0  929   
922  0  0  0  0  0  0   0    0     0  0   ...     0  930   
923  0  0  0  0  0  0   0    0     0  0   ...     0  931   
924  0  0  0  0  0  0   0    0     0  0   ...     0  932   
925  0  0  0  0  0  0   0    0     0  0   ...     0  933   
926  0  0  0  0  0  0   0    0     0  0   ...     0  934   
927  0  0  0  0  0  0   0    0     0  0   ...     0  935   
928  0  0  0  0  0  0   0    0     0  0   ...     0  936   
929  0  0  0  0  0  0   0    0     0  0   ...     0  937   
930  0  0  0  0  0  0   0    0     0  0   ...     0  938   
931  0  0  0  0  0  0   0    0     0  0   ...     0  939   
932  0  0  0  0  0  0   0    0     0  0   ...     0  940   
933  0  0  0  0  0  0   0    0     0  0   ...     0  941   
934  0  0  0  0  0  0   0    0     0  0   ...     0  942   
935  0  0  0  0  0  0   0    0     0  0   ...     0  943   
936  0  0  0  0  0  0   0    0     0  0   ...     0  944   
937  0  0  0  0  0  0   0    0     0  0   ...     0  945   
938  0  0  0  0  0  0   0    0     0  0   ...     0  946   
939  0  0  0  0  0  0   0    0     0  0   ...     0  947   
940  0  0  0  0  0  0   0    0     0  0   ...     0  948   

                                          text  a  b  c  d  e  f   label  
0                                        そうっすね  0  1  2  0  0  0   12000  
1                           そこは話が変わるので一旦スコープ外で  0  0  0  0  0  2       2  
2                               さっき話していた感じで良くて  0  2  0  0 

In [41]:
#tmp_label = dataset_label.label.value_counts()
#tmp_label.to_csv('tmp_label_2.csv', encoding="shift-jis")
tmp_label = pd.read_csv("tmp_label_2.csv", encoding="shift_jis")
tmp_label

label  count  label_id_def  label_id
0   210000      1            52         0
1   202000      2            43         0
2   201000      1            59         0
3   200200      3            35         0
4   200100      4            30         0
5   200020      1            62         0
6   200010      1            55         0
7   200001      1            60         0
8   200000     96             3         0
9   110200      2            48         3
10  110000      3            34         0
11  102002      1            64         5
12  102000      2            44         2
13  101010      1            66         0
14  101001      1            65         0
15  101000      2            47         0
16  100200     14            10         3
17  100100      7            17         0
18  100002      5            26         5
19  100001      4            33         0
20  100000      3            40         0
21   22020      2            49         4
22   22000     13            11         1
23   21000      7            16         1
24   20200      6            22         1
25   20100      5            27         1
26   20001      5            23         1
27   20000     48             6         1
28   12000     21             8         2
29   11000      5            25         2
..     ...    ...           ...       ...
37   10000      3            37         1
38    2200      1            57         2
39    2020     10            14         2
40    2010      1            53         2
41    2002      4            31         5
42    2001      2            45         2
43    2000     67             4         2
44    1200      1            58         3
45    1100      1            51         3
46    1020      1            67         4
47    1002      1            63         5
48    1001      3            38         5
49    1000      6            19         2
50     220      3            41         3
51     202      4            29         3
52     201      6            20         3
53     200    124             1         3
54     120      5            24         4
55     110      3            36         3
56     102      6            21         5
57     101      1            56         3
58     100     12            12         3
59      22      1            54         4
60      21      2            46         4
61      20     30             7         4
62      12      3            39         5
63      10      6            18         4
64       2     98             2         5
65       1     19             9         5
66       0     64             5         6

[67 rows x 4 columns]

In [65]:
dataset = pd.merge(dataset_label, tmp_label, how="outer", on="label")
dataset

・  .  %  ％  0  1  10  100  1000  2    ...     a  b  c  d  e  f   label  \
0    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
1    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
2    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
3    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
4    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
5    0  0  0  0  0  1   0    0     0  1    ...     0  1  2  0  0  0   12000   
6    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
7    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
8    0  0  0  0  0  0   0    0     0  0    ...     0  2  1  0  0  0   12000   
9    0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
10   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
11   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
12   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
13   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
14   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
15   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
16   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
17   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
18   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
19   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
20   0  0  0  0  0  0   0    0     0  0    ...     0  1  2  0  0  0   12000   
21   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
22   0  0  0  0  0  0   1    1     0  0    ...     0  0  0  0  0  2       2   
23   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
24   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
25   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
26   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
27   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
28   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
29   0  0  0  0  0  0   0    0     0  0    ...     0  0  0  0  0  2       2   
..  .. .. .. .. .. ..  ..  ...   ... ..    ...    .. .. .. .. .. ..     ...   
911  0  0  0  0  0  0   0    0     0  0    ...     2  0  0  2  0  0  200200   
912  0  0  0  0  0  0   0    0     0  0    ...     2  0  0  2  0  0  200200   
913  0  0  0  0  0  0   0    0     0  0    ...     2  0  0  2  0  0  200200   
914  0  0  0  0  0  0   0    0     0  0    ...     2  0  0  0  0  1  200001   
915  0  0  0  0  0  0   0    0     0  0    ...     0  1  0  2  0  2   10202   
916  0  0  0  0  0  0   0    0     0  0    ...     0  0  2  0  0  2    2002   
917  0  0  0  0  0  0   0    0     0  0    ...     0  0  2  0  0  2    2002   
918  0  0  0  0  0  0   0    0     0  0    ...     0  0  2  0  0  2    2002   
919  0  0  0  0  0  0   0    0     0  0    ...     0  0  2  0  0  2    2002   
920  0  0  0  0  0  0   0    0     0  0    ...     0  0  2  0  1  0    2010   
921  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  1     101   
922  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
923  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
924  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
925  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
926  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
927  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
928  0  0  0  0  0  0   0    0     0  0    ...     0  0  0  1  0  0     100   
929  0  0  0  0  0  0   0    0     0  0    ...     0  0

In [66]:
x, y_f = dataset.drop(["text","id", "label", "a", "b", "c", "d", "e", "f", "count", "label_id", "label_id_def",], axis=1).values, dataset["label_id"].values

In [67]:
y = y_f.astype(np.int32)

In [68]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2,
       2, 2,

In [47]:
test_data = dataset.drop(["text","id", "label", "a", "b", "c", "d", "e", "f", "count", "label_id", "label_id_def"], axis=1)
test_data = test_data[0:1]
#for i in range(len(test_data.columns) - 1):
#    test_data[0,i] = 0
test_data.loc[0,:] = 0
test_data.sum(axis=1)

0    0
dtype: int64

In [48]:
test_data

・  .  %  ％  0  1  10  100  1000  2 ...  労働  論  論点  論理  話  話し  話そ  話題  枠  綺麗
0  0  0  0  0  0  0   0    0     0  0 ...   0  0   0   0  0   0   0   0  0   0

[1 rows x 1155 columns]

In [49]:
test_data.to_csv('col_name_test9.csv', encoding="shift-jis")
col_name_test = pd.read_csv('col_name_test9.csv', encoding="shift-jis")

In [50]:
#col_name_test = col_name_test.drop([0,192,25,187,413], axis=1)
col_name_test.sum(axis=1)
col_name_test.to_csv('col_name_test.csv', encoding="shift-jis")

In [53]:
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix
from sklearn.semi_supervised import LabelPropagation, LabelSpreading
from sklearn.cross_validation import cross_val_scoreimport MeCab
import chainer
from chainer import training
from chainer.training import extensions
import chainer.links as L
import chainer.functions as F
from chainer.datasets import tuple_dataset

mecab = MeCab.Tagger("-Ochasen")
col_name = pd.read_csv("termDF_conName.csv", encoding="shift_jis", header=1)
col_name_test = pd.read_csv('col_name_test.csv', encoding="shift-jis")
#col_name_test.loc[0,:] = 0
#col_name_test = col_name_test.drop(["id"], axis=1)
#col_name.TERM
#vardata.T
tmp_col_name_test = col_name_test
raw_string = u"今日はいい天気ですね"
mt = MeCab.Tagger('mecabrc')
mt.parse('')

node = mt.parseToNode(raw_string)
text = np.array([])
#words, nouns = get_surfaces(node), get_nouns(node)
while node:
    text = np.append(text, node.surface)
#    if node.feature.startswith('名詞'):
    print(node.surface) # <= 文字が取得できる！
#    print(node.feature)
    node = node.next
for i in range(len(text)-1):
    for j in range(len(tmp_col_name_test.columns) - 1):
        if text[i] ==  tmp_col_name_test.columns[j]:
            tmp_col_name_test.loc[0,j] = 1 



SyntaxError: invalid syntax (<ipython-input-53-fab8fad5ed3e>, line 4)

In [54]:
#col_name = col_name.drop(["id"], axis=1)
col_name


NameError: name 'col_name' is not defined

In [51]:
for i in range(len(col_name_test.columns) - 1):
    col_name_test[0,i] = 0


In [52]:
col_name_test.sum(axis=1)

0    0
dtype: int64

In [57]:
len(text)

NameError: name 'text' is not defined

In [53]:
col_name_test.loc[0,:] = 0

In [54]:
col_name_test.columns[0]

'Unnamed: 0'

In [60]:
while node:
    print(node.nouns) # <= 文字が取得できる！
    node = node.next

NameError: name 'node' is not defined

In [61]:
os.listdir()

['.DS_Store',
 '.ipynb_checkpoints',
 '.RData',
 '.Rhistory',
 'base.R',
 'col_name_test.csv',
 'col_name_test2.csv',
 'col_name_test4.csv',
 'col_name_test5.csv',
 'col_name_test7.csv',
 'data_labelpropagation_check.csv',
 'data_matrics.csv',
 'dataset.R',
 'featurelist.csv',
 'label.csv',
 'learningdata.csv',
 'logs',
 'mymodel.npz',
 'mymodel2.npz',
 'mymodel4.npz',
 'mymodel5.npz',
 'mymodel6.npz',
 'Preprocess.R',
 'temp_textdata.csv',
 'temp_textdata1.csv',
 'temp_textdata_2.csv',
 'termDF_conName.csv',
 'text mining.ipynb',
 'textdata_5100.csv',
 'textdata_5100_utf.csv',
 'tmp_label.csv',
 'tmp_label_2.csv',
 'topicmodel.R',
 'train.py',
 'train_data_1.csv',
 'train_data_2.csv',
 'train_data_2.txt',
 'train_data_4.csv',
 'train_label_2.csv',
 'Untitled.ipynb',
 'vardata_2.csv',
 'vardata_3.csv',
 'vardata_4.csv']

In [55]:
#dataset = pd.read_csv("train_data_2.txt", encoding="shift-jis")
tmp_label_id = pd.read_csv("tmp_label.csv", encoding="shift_jis")

In [88]:
train_data_2 = pd.read_csv("train_label_2.csv", encoding="shift_jis")
#vardata = pd.read_csv("vardata_2.csv", encoding="shift_jis")
train_data_2

id   label  a  b  c  d  e  f
0      1   12000  0  1  2  0  0  0
1      2       2  0  0  0  0  0  2
2      3   20001  0  2  0  0  0  1
3      4   10001  0  1  0  0  0  1
4      5   10001  0  1  0  0  0  1
5      6  200000  2  0  0  0  0  0
6      7       1  0  0  0  0  0  1
7      8    2000  0  0  2  0  0  0
8      9  200000  2  0  0  0  0  0
9     10    2000  0  0  2  0  0  0
10    11  100001  1  0  0  0  0  1
11    12  200000  2  0  0  0  0  0
12    13    2000  0  0  2  0  0  0
13    14  200000  2  0  0  0  0  0
14    15   10200  0  1  0  2  0  0
15    16   10001  0  1  0  0  0  1
16    17   11000  0  1  1  0  0  0
17    18      20  0  0  0  0  2  0
18    19       2  0  0  0  0  0  2
19    20  100001  1  0  0  0  0  1
20    21      20  0  0  0  0  2  0
21    22  100200  1  0  0  2  0  0
22    23      21  0  0  0  0  2  1
23    24    2000  0  0  2  0  0  0
24    25    2000  0  0  2  0  0  0
25    26   10002  0  1  0  0  0  2
26    27     201  0  0  0  2  0  1
27    28  102000  1  0  2  0  0  0
28    29   10200  0  1  0  2  0  0
29    30     201  0  0  0  2  0  1
..   ...     ... .. .. .. .. .. ..
551  552  200000  2  0  0  0  0  0
552  553       0  0  0  0  0  0  0
553  554       2  0  0  0  0  0  2
554  555     100  0  0  0  1  0  0
555  556  200000  2  0  0  0  0  0
556  557   20000  0  2  0  0  0  0
557  558  200000  2  0  0  0  0  0
558  559     200  0  0  0  2  0  0
559  560   20000  0  2  0  0  0  0
560  561       0  0  0  0  0  0  0
561  562  200000  2  0  0  0  0  0
562  563       2  0  0  0  0  0  2
563  564       2  0  0  0  0  0  2
564  565       2  0  0  0  0  0  2
565  566       2  0  0  0  0  0  2
566  567   20000  0  2  0  0  0  0
567  568       2  0  0  0  0  0  2
568  569       2  0  0  0  0  0  2
569  570     200  0  0  0  2  0  0
570  571     200  0  0  0  2  0  0
571  572     200  0  0  0  2  0  0
572  573       2  0  0  0  0  0  2
573  574       2  0  0  0  0  0  2
574  575   20000  0  2  0  0  0  0
575  576     200  0  0  0  2  0  0
576  577     200  0  0  0  2  0  0
577  578       1  0  0  0  0  0  1
578  579       0  0  0  0  0  0  0
579  580     200  0  0  0  2  0  0
580  581       2  0  0  0  0  0  2

[581 rows x 8 columns]

In [153]:
dataset_label = pd.merge(col_name, train_data_2, how="outer", on="id")
dataset_label

NameError: name 'col_name' is not defined

In [57]:
dataset = pd.merge(dataset_label, tmp_label_id, how="outer", on="label")
dataset

・  .  %  ％  0  1  10  100  1000  2      ...       a  b  c  d  e  f  \
0    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
1    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
2    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
3    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
4    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
5    0  0  0  0  0  1   0    0     0  1      ...       0  1  2  0  0  0   
6    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
7    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
8    0  0  0  0  0  0   0    0     0  0      ...       0  2  1  0  0  0   
9    0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
10   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
11   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
12   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
13   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
14   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
15   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
16   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
17   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
18   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
19   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
20   0  0  0  0  0  0   0    0     0  0      ...       0  1  2  0  0  0   
21   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
22   0  0  0  0  0  0   1    1     0  0      ...       0  0  0  0  0  2   
23   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
24   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
25   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
26   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
27   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
28   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
29   0  0  0  0  0  0   0    0     0  0      ...       0  0  0  0  0  2   
..  .. .. .. .. .. ..  ..  ...   ... ..      ...      .. .. .. .. .. ..   
911  0  0  0  0  0  0   0    0     0  0      ...       2  0  0  2  0  0   
912  0  0  0  0  0  0   0    0     0  0      ...       2  0  0  2  0  0   
913  0  0  0  0  0  0   0    0     0  0      ...       2  0  0  2  0  0   
914  0  0  0  0  0  0   0    0     0  0      ...       2  0  0  0  0  1   
915  0  0  0  0  0  0   0    0     0  0      ...       0  1  0  2  0  2   
916  0  0  0  0  0  0   0    0     0  0      ...       0  0  2  0  0  2   
917  0  0  0  0  0  0   0    0     0  0      ...       0  0  2  0  0  2   
918  0  0  0  0  0  0   0    0     0  0      ...       0  0  2  0  0  2   
919  0  0  0  0  0  0   0    0     0  0      ...       0  0  2  0  0  2   
920  0  0  0  0  0  0   0    0     0  0      ...       0  0  2  0  1  0   
921  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  1   
922  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
923  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
924  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
925  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
926  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
927  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
928  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
929  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
930  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
931  0  0  0  0  0  0   0    0     0  0      ...       0  0  0  1  0  0   
932  0  0  0  0  0  0   0    0

In [58]:
x, y_f = dataset.drop(["id", "label", "a", "b", "c", "d", "e", "f", "count_label", "label_id", "label_id_def"], axis=1).values, dataset["label_id"].values

In [69]:
#dataset = pd.merge(vardata, train_data_2, how="outer", on="id")
y = y_f.astype(np.int32)

In [70]:
len(y)

941

In [71]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)

In [72]:
import chainer
from chainer import training
from chainer.training import extensions
import chainer.links as L
import chainer.functions as F
from chainer.datasets import tuple_dataset


In [73]:
class MLP(chainer.Chain):
    def __init__(self, n_in, n_out):
        super(MLP, self).__init__(
            l1=L.Linear(n_in, 2000),
            l2=L.Linear(2000, 1000),
            l3=L.Linear(1000, 500),
            l4=L.Linear(500, n_out),
        )
    def __call__(self, x):
        h = F.relu(self.l1(x))
        h = F.relu(self.l2(h))
        h = F.relu(self.l3(h))
        h = self.l4(h)
        return h

###### 3層 + BatchNormalization
class MLP_bnorm(chainer.Chain):
    def __init__(self, n_in, n_out):
        super(MLP_bnorm, self).__init__(
            l1=L.Linear(n_in, 1000),
            l2=L.Linear(1000, 1000),
            l3=L.Linear(1000, 500),
            l4=L.Linear(500, n_out),
            bnorm1 = L.BatchNormalization(1000),
            bnorm2 = L.BatchNormalization(1000),
            bnorm3 = L.BatchNormalization(500),
        )
    def __call__(self, x):
        h = F.relu(self.bnorm1(self.l1(x)))
        h = F.relu(self.bnorm2(self.l2(h)))
        h = F.relu(self.bnorm3(self.l3(h)))
        h = self.l4(h)
        return h
        
###### 3層 + BatchNormalization + Dropout
class MLP_bnorm_dropout(chainer.Chain):
    def __init__(self, n_in, n_out):
        super(MLP_bnorm_dropout, self).__init__(
            l1=L.Linear(n_in, 2000),
            l2=L.Linear(2000, 1000),
            l3=L.Linear(1000, 500),
            l4=L.Linear(500, n_out),
            bnorm1 = L.BatchNormalization(2000),
            bnorm2 = L.BatchNormalization(1000),
            bnorm3 = L.BatchNormalization(500),
        )
    def __call__(self, x):
        h = F.dropout(F.relu(self.bnorm1(self.l1(x))), ratio=0.5) #v2からtrain引数は不要なので注意
        h = F.dropout(F.relu(self.bnorm2(self.l2(h))), ratio=0.5)
        h = F.dropout(F.relu(self.bnorm3(self.l3(h))), ratio=0.5)
        h = self.l4(h)
        return h


In [74]:
#vardata = pd.read_csv("vardata_2.csv", encoding="shift_jis")
#tmp_label.to_csv('tmp_label.csv')

In [75]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [76]:
tmp_label = dataset.label.value_counts()
#tmp_label.reset_index


In [77]:
y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2,
       2, 2,

In [78]:
train = tuple_dataset.TupleDataset(x.astype(np.float32), y.astype(np.int32))
test = tuple_dataset.TupleDataset(x_test.astype(np.float32), y_test.astype(np.int32))

In [83]:
#model = L.Classifier(MLP(638,62))
#model = L.Classifier(MLP_bnorm(638, 62))
#model = L.Classifier(MLP_bnorm_dropout(638, 62))
#model = L.Classifier(MLP(638,7))
#model = L.Classifier(MLP_bnorm(638, 7))
model = L.Classifier(MLP_bnorm_dropout(1155, 7))

In [84]:
optimizer = chainer.optimizers.MomentumSGD(lr=0.01)
#optimizer = chainer.optimizers.MomentumSGD(lr=0.001)
optimizer.setup(model)

In [85]:
train_iter = chainer.iterators.SerialIterator(train, 20)
test_iter = chainer.iterators.SerialIterator(test, 20, repeat=False, shuffle=False)

######### 学習用のパラメータ設定
updater = training.StandardUpdater(train_iter, optimizer, device=-1)
trainer = training.Trainer(updater, (30, 'epoch'), out="logs")
trainer.extend(extensions.Evaluator(test_iter, model, device=-1))
trainer.extend(extensions.LogReport())
trainer.extend(extensions.PrintReport(['epoch', 'main/loss', 'validation/main/loss', 'main/accuracy', 'validation/main/accuracy']))
trainer.extend(extensions.ProgressBar())                                                                                          


In [86]:
trainer.run()

epoch       main/loss   validation/main/loss  main/accuracy  validation/main/accuracy
1           2.40526     1.7823                0.153125       0.346111                  
2           2.32856     1.49321               0.22234        0.458333                  
     total [###...............................................]  7.08%
this epoch [######............................................] 12.54%
       100 iter, 2 epoch / 30 epochs
       inf iters/sec. Estimated time to finish: 0:00:00.
3           2.21083     1.32291               0.26383        0.549444                  
4           2.14136     1.13813               0.297872       0.589444                  
     total [#######...........................................] 14.17%
this epoch [############......................................] 25.08%
       200 iter, 4 epoch / 30 epochs
     17.27 iters/sec. Estimated time to finish: 0:01:10.149983.
5           1.89498     0.864824              0.385106       0.685556              

In [87]:
def eval_score(y_true, y_pred):
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    conf_mat = confusion_matrix(y_true, y_pred)
    print("precision : %04f" % prec)
    print("recall    : %04f" % rec)
    print("accuracy  : %04f" % acc)
    print("f1        : %04f" % f1)
    print("confusion_matrix : ")
    print(confusion_matrix(y_true, y_pred))
    return {"1_prec": prec, "2_rec": rec, "3_acc":acc, "4_f1":f1, "5_conf_mat":conf_mat}


In [88]:
with chainer.using_config('train', False):
    # 学習
    y_train_pre = F.softmax(model.predictor(x_train.astype(np.float32))).data.argmax(axis=1)
    eval_score(y_train, y_train_pre)
    # テスト
    y_test_pre = F.softmax(model.predictor(x_test.astype(np.float32))).data.argmax(axis=1)
    eval_score(y_test, y_test_pre)


precision : 0.984345
recall    : 0.982713
accuracy  : 0.982713
f1        : 0.983059
confusion_matrix : 
[[105   0   1   0   0   0   3]
 [  0  97   0   0   0   0   2]
 [  0   0  98   0   0   0   1]
 [  0   0   0 164   0   0   2]
 [  0   0   1   0  68   0   0]
 [  0   0   2   0   0 143   1]
 [  0   0   0   0   0   0  64]]
precision : 0.981104
recall    : 0.978836
accuracy  : 0.978836
f1        : 0.979488
confusion_matrix : 
[[34  0  0  0  0  0  1]
 [ 0 21  0  0  0  0  0]
 [ 0  0 37  0  0  0  0]
 [ 0  0  0 36  0  0  0]
 [ 0  0  0  0 10  0  1]
 [ 0  0  0  0  0 36  1]
 [ 1  0  0  0  0  0 11]]


/Users/takumasaito/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sklearn/metrics/classification.py:1203: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sample_weight=sample_weight)
/Users/takumasaito/.pyenv/versions/3.5.1/lib/python3.5/site-packages/sklearn/metrics/classification.py:1304: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring=

In [89]:
from chainer import serializers

gpu = 0

#model = L.Classifier(MLP_bnorm_dropout(638, 7))
#model = myDNN(100, 500, 10)
#chainer.cuda.get_device(gpu).use()
#model.to_gpu(gpu) # GPUを使うための処理

# -----------------------------
#         学習とかの処理
# -----------------------------

model.to_cpu() # CPUで計算できるようにしておく
serializers.save_npz("mymodel9.npz", model) # npz形式で書き出し

In [109]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])